Check if prune script exists

diff --git a/qgm-unc-prune b/qgm-unc-prune
--- a/qgm-unc-prune
+++ b/qgm-unc-prune
@@ -18,13 +18,16 @@ if [ $DRYRUN == "true" ]; then
 fi
 echo "-------------------------------------------"
 
-sed "s/^var days=.*$/var days=${DAYS};/" ${LIBDIR}/prune_unc.js > $EXECCONF
-sed -i "s/^var dryrun=.*$/var dryrun=${DRYRUN};/" $EXECCONF
-
-
-mongo --port 27117 < $EXECCONF
-
-rm $EXECCONF
+if [ -f ${LIBDIR}/prune_unc.js ]; then 
+    echo "Prune script not found in ${LIBDIR}/prune_unc.js"
+    echo "Exiting."
+    exit 1
+else
+    sed "s/^var days=.*$/var days=${DAYS};/" ${LIBDIR}/prune_unc.js > $EXECCONF
+    sed -i "s/^var dryrun=.*$/var dryrun=${DRYRUN};/" $EXECCONF
+    mongo --port 27117 < $EXECCONF
+    rm $EXECCONF
+fi
 
 
 
